# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbiasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=50)),
                ('json', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
